project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: packages.qmd
        text: Packages
      - href: tutorials.qmd
        text: Tutorials
      - href: presentations.qmd
        text: Presentations
    right:
      - icon: envelope-fill
        href: mailto:brady.rippon@gmail.com
      - text: "<i class='ai ai-google-scholar'></i>"
        href: https://scholar.google.com/citations?user=dFCzy7wAAAAJ&hl=en
      - icon: linkedin
        href: https://linkedin.com/in/brady-rippon/
      - icon: github
        href: https://github.com/bradyrippon

format:
  html:
    theme: cosmo 
    css: styles.css
    toc: false
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
