project:
  type: website
  output-dir: docs

website:
  title: "Brady Rippon"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: about.qmd
        text: About
        
      - href: packages.qmd
        text: Packages

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

